# Generated by Django 5.1.3 on 2024-11-08 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nacionalidade', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('idade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_lancamento', models.DateField()),
                ('diretor', models.CharField(max_length=150)),
                ('nome_original', models.CharField(max_length=150)),
                ('elenco', models.ManyToManyField(related_name='filmes', to='app.ator')),
                ('genero', models.ManyToManyField(related_name='filmes', to='app.genero')),
                ('poster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster_filme', to='app.poster')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ano_lancamento', models.CharField(max_length=4)),
                ('ano_final', models.CharField(blank=True, max_length=4, null=True)),
                ('criador', models.CharField(max_length=150)),
                ('nome_original', models.CharField(max_length=150)),
                ('elenco', models.ManyToManyField(related_name='series', to='app.ator')),
                ('genero', models.ManyToManyField(related_name='series', to='app.genero')),
                ('poster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster_serie', to='app.poster')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmes_favoritas', models.ManyToManyField(related_name='filmes_favoritos', to='app.filme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('series_favoritas', models.ManyToManyField(related_name='series_favoritas', to='app.serie')),
            ],
        ),
    ]
