# Generated by Django 5.1.3 on 2024-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nacionalidade', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('idade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdutorSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nacionalidade', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('idade', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='filmes_favoritas',
            new_name='filmes_favoritos',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='diretor',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='criador',
        ),
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.ManyToManyField(related_name='diretores', to='app.diretor'),
        ),
        migrations.AddField(
            model_name='serie',
            name='criador',
            field=models.ManyToManyField(related_name='produtores', to='app.produtorserie'),
        ),
    ]
