# Generated by Django 5.1.3 on 2024-11-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_diretor_produtorserie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='diretor',
            field=models.ManyToManyField(related_name='filmes_dirigidos', to='app.diretor'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='elenco',
            field=models.ManyToManyField(related_name='filmes_participados', to='app.ator'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.ManyToManyField(related_name='filmes_genero', to='app.genero'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='poster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filme', to='app.poster'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='foto',
            field=models.ImageField(upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='criador',
            field=models.ManyToManyField(related_name='series_criadas', to='app.produtorserie'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='elenco',
            field=models.ManyToManyField(related_name='series_participadas', to='app.ator'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='genero',
            field=models.ManyToManyField(related_name='series_genero', to='app.genero'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='poster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serie', to='app.poster'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.perfil')),
                ('filme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.filme')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.serie')),
            ],
        ),
    ]
