# Generated by Django 5.1.3 on 2024-11-08 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_filme_diretor_alter_filme_elenco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='filme',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='filmes_favoritos',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='elenco',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='series_favoritas',
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_lancamento', models.DateField()),
                ('tipo', models.CharField(choices=[('FILME', 'Filme'), ('SERIE', 'Série')], max_length=5)),
                ('nome_original', models.CharField(max_length=150)),
                ('diretor', models.ManyToManyField(related_name='filmes_dirigidos', to='app.diretor')),
                ('elenco', models.ManyToManyField(related_name='filmes_participados', to='app.ator')),
                ('genero', models.ManyToManyField(related_name='filmes_genero', to='app.genero')),
                ('poster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filme', to='app.poster')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='Producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.producao'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='producoes_favoritas',
            field=models.ManyToManyField(related_name='series_favoritas', to='app.producao'),
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
